id = "dbml"
name = "DBML"
description = "Database Markup Language (DBML) support."
version = "0.0.1"
schema_version = 1
authors = ["Ayush Shukla <ayush@shuklaayu.sh>"]
repository = "https://github.com/shuklaayush/zed-dbml"

[grammars.dbml]
repository = "https://github.com/dynamotn/tree-sitter-dbml"
commit = "2e2fa5640268c33c3d3f27f7e676f631a9c68fd9"
